name: Build
on: [push]
jobs:
  build:
    runs-on: [ubuntu-latest] 
    steps:
      - name: Autobuild 
        uses: AlchemyViewer/action-autobuild@v4
        with:
          platform: common

      - name: Publish
        uses: AlchemyViewer/action-autobuild-release@v4
        if: startsWith(github.ref, 'refs/tags/v')
